version: '3'
services:
  book_catalog:
    image: book_catalog:latest
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: book_catalog_cntr
    ports:
     - "4002:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722_part3_ys57_user:0be7umVCZqFj3J1VZEgoqhCJnxZ1gFNl@dpg-crifqajv2p9s738hitig-a.oregon-postgres.render.com/sit722_part3_ys57
    restart: "no"

  inventory_management:
    image: inventory_management:latest
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: inventory_management_cntr
    ports:
     - "4003:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://sit722_part3_ys57_user:0be7umVCZqFj3J1VZEgoqhCJnxZ1gFNl@dpg-crifqajv2p9s738hitig-a.oregon-postgres.render.com/sit722_part3_ys57
    restart: "no"